
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=andrei
      - POSTGRES_PASSWORD=leprechaun1
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgad:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=main@mail.com
      - PGADMIN_DEFAULT_PASSWORD=toor
    ports:
      - 5050:80